### ISSUE TITLE
(#5) FreePostsApi 기능 수정/추가

### ISSUE THREAD

**Issue by nswon** [wonyongChoi05/Ber#15]
1. 전체조회 기능 추가
2. title 단건 조회 수정
@wonyongChoi05

**Comment by wonyongChoi05** [comment]
굿 이슈 해결하면 내가 올린 이슈 closed issue 하면 됨 !!
이슈 닫아도 히스토리에서 볼 수 있음 !!

**Comment by wonyongChoi05** [comment]
이슈에 라벨 달고 2개 다 닫아주세요 !!!
